SalesforceFoundation/PMM

- force-app/main/default/reports/ProgramManagementReports/Client_Records_with_Missing_Phone_Number.report-meta.xml
- We added a new filter to filter by Client to the report, Client Records with Missing Phone Number.
- We changed the existing filter on the report, Client Records with Missing Phone Number to show only 'My Contacts'  instead of 'All Accounts.'
Fixes - #188
> Fix filter on client records with missing phone number

- force-app/main/default/staticresources/pmm/bsdtOverrides.css
- We removed scrolling on the Bulk Service Delivery Tool to allow the date popup to successfully record the Service Delivery Date.
> Remove scrolling on BSDT to fix date popup

- force-app/main/default/classes/FeatureParameters.cls
- force-app/main/default/classes/FeatureParameters_TEST.cls
- force-app/main/default/classes/InstallScript_TEST.cls
- force-app/main/default/classes/QueryBuilder.cls
- force-app/main/default/classes/QueryBuilder_TEST.cls
- force-app/main/default/featureParameters/ActiveProgramsWithEngagementsLast30.featureParameterInteger-meta.xml
- Added a Feature Parameter, type integer, to capture the count of Active Programs with Program Engagements created in the Last 30 Days. For more information about telemetry, look for the PMM Feature Telemetry article in the [Program Management Module Documentation](https://powerofus.force.com/PMM_Documentation)
> Add Telemetry Count for Active Programs with Program Engagements

- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
- force-app/main/default/objects/ServiceDelivery__c/fieldSets/Default.fieldSet-meta.xml
- BSDT defaults to Unit of Measure label "Quantity" when none is defined on the Service record.
> default to Quantity label if no UoM defined on Service

- robot/pmm/resources/pmm_locators.py
- robot/pmm/tests/browser/ProgramEngagement/ProgramEngagement.robot
1. Added date validation test for program engagement
2. Updated existing create new program engagement test to use wait for modal keyword
3. Fixed keyword case on programengagement.robot file
> add date validation for PE

- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
When a contact and service field are on the field set and the user is using the Manage Services button on caseman, the service field is now enabled and is a lookup.
~~- [ ] PR contains draft release notes~~
> BSDT bug fix 

- force-app/main/default/objects/ProgramEngagement__c/fields/Stage__c.field-meta.xml
- We added a new  Program Engagement Stage called Waitlisted so users can track contacts waitlisted for a Program. Existing customers are strongly encouraged to add this picklist value to the Program Engagement Stage field if it suits their needs.
> Add PE waitlisted stage

- cumulusci.yml
- force-app/main/default/quickActions/ProgramEngagement__c.CreateServiceDelivery.quickAction-meta.xml
- To streamline data entry, PMM now populates the Client field on the Program Engagement record when users create a Service Delivery from the Program Engagement record.
> Auto populate contact

- force-app/main/default/classes/FeatureParameters.cls
- force-app/main/default/classes/FeatureParameters_TEST.cls
- force-app/main/default/featureParameters/PermSetDeliverUsers.featureParameterInteger-meta.xml
- force-app/main/default/featureParameters/PermSetManageUsers.featureParameterInteger-meta.xml
- Added a new Feature Parameter that returns a count of how many Users are assigned the PMM: Deliver permission.
- Added a new Feature Parameter that returns a count of how many Users are assigned the PMM: Manage permission.
-We updated PMM Feature Telemetry to include a count of Users assigned the PMM: Deliver permission, and a count of Users assigned the PMM: Manage permission. No personally identifiable information is collected through PMM Feature Telemetry. Read more about [PMM Feature Telemetry](https://powerofus.force.com/s/article/PMM-Feature-Telemetry).
~~Place holder data is incorporated (Refer to [Case Management Sample Data …
> Add Feature Parameters to Count Permission Set Assignments

- unpackaged/config/dev/flows/Auto_Populate_Date_And_Name_On_Program_Engagement.flow-meta.xml
When a new program Engagement record is created with 'Active' status and is associated to a program whose start date is earlier than or equal to today , the Start date on the program engagement record is set to Today.
~~- [ ] …
> Update StartDate population on Program Engagement

- .flake8
- .github/workflows/lockfile-lint.yml
- .lintstagedrc
- .prettierignore
- cumulusci.yml
- force-app/main/default/flexipages/Bulk_Service_Deliveries.flexipage-meta.xml
- force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Program_Cohort_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Program_Engagement_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Program_Management_Home.flexipage-meta.xml
- force-app/main/default/flexipages/Program_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Service_Delivery_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Service_Record_Page.flexipage-meta.xml
- jest.config.js
- package.json
- pyproject.toml
- sfdx-project.json
- yarn.lock
This PR clears security warnings in obsolete dependencies by updating to the latest lwc-jest package. In order to support this package, sfdx-project.json was also updated to version 49.0, and changes were made to FlexiPage metadata to comply with API 49.0 expectations. This change does require QA.
Note: this PR may require you to update your Node version.
> Clear vulns via NPM updates

- cumulusci.yml
- force-app/main/default/flows/Auto_Populate_Date_And_Name_On_Program_Engagement.flow-meta.xml
Now when the program has an earlier start date, and the stage is Active then the program engagement start date is autopopulated to 'Today'
> Fix Program Engagement Process Builder

- force-app/main/default/aura/createServiceSchedule/createServiceSchedule.cmp
- force-app/main/default/aura/createServiceSchedule/createServiceScheduleController.js
- force-app/main/default/aura/createServiceSchedule/createServiceScheduleHelper.js
- force-app/main/default/classes/ServiceScheduleCreatorController.cls
- force-app/main/default/classes/ServiceScheduleCreatorController_TEST.cls
- force-app/main/default/classes/ServiceScheduleModel.cls
- force-app/main/default/classes/ServiceScheduleService.cls
- force-app/main/default/classes/ServiceScheduleService_TEST.cls
- force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
- Allow and respect record type selections for Service Schedule
- Fix issue where New button when clicked on from the List View did not show modal after modal was previously closed.
~~Update & Test permission sets to account for new features and CRUD/FLS~~
> Respect record types when added by customer

- force-app/main/default/classes/AttendanceSelector.cls
- force-app/main/default/classes/AttendanceService.cls
- force-app/main/default/classes/AttendanceService_TEST.cls
- force-app/main/default/layouts/ServiceSchedule__c-Service Schedule Layout.layout-meta.xml
- force-app/main/default/layouts/ServiceSession__c-Service Session Layout.layout-meta.xml
- force-app/main/default/lwc/attendance/attendance.js
- force-app/main/default/lwc/attendanceRow/attendanceRow.js
- force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
- force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
- force-app/main/default/lwc/participantSelector/participantSelector.css
- force-app/main/default/objects/ServiceSchedule__c/fieldSets/ServiceScheduleInformation.fieldSet-meta.xml
- force-app/main/default/objects/ServiceSchedule__c/fields/DefaultServiceQuantity__c.field-meta.xml
- force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
- In Service Schedule Creator, a Default Service Quantity field will now appear. When filled in, attendance for that schedule will have that value pre-populated for Quantity.
> Default Service Quantity support for schedules and attendance

- force-app/main/default/classes/ServiceScheduleModel.cls
- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/layouts/ServiceSchedule__c-Service Schedule Layout.layout-meta.xml
- force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
- force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
- force-app/main/default/objects/ServiceSchedule__c/fields/Interval__c.field-meta.xml
- Add 'Every N Days/Weeks/Months' options to Service Schedule Wizard
- ~~Place holder data is incorporated (Refer to [Case Management Sample Data document](https://quip.com/cbFcAPJF8t0z))~~
- ~~Base axe-core JEST test included for any new LWC (No critical violations)~~
- ~~Permission sets & field sets are updated to account for CRUD/FLS/TABS for new object metadata~~
> Add 'Every N Days/Weeks/Months' options to Service Schedule Wizard

- force-app/main/default/aura/addMoreParticipants/addMoreParticipants.cmp
- force-app/main/default/aura/addMoreParticipants/addMoreParticipants.cmp-meta.xml
- force-app/main/default/aura/addMoreParticipants/addMoreParticipantsController.js
- force-app/main/default/aura/deleteFutureSessions/deleteFutureSessions.cmp
- force-app/main/default/aura/deleteFutureSessions/deleteFutureSessionsController.js
- force-app/main/default/classes/ProgramTestDataFactory.cls
- force-app/main/default/classes/ServiceScheduleCreatorController.cls
- force-app/main/default/classes/ServiceScheduleCreatorController_TEST.cls
- force-app/main/default/classes/ServiceScheduleDomain.cls
- force-app/main/default/classes/ServiceScheduleDomain_TEST.cls
- force-app/main/default/classes/ServiceScheduleService.cls
- force-app/main/default/classes/ServiceScheduleService_TEST.cls
- force-app/main/default/classes/ServiceSelector.cls
- force-app/main/default/classes/ServiceSelector_TEST.cls
- force-app/main/default/flexipages/Service_Schedule_Record_Page.flexipage-meta.xml
- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/layouts/ServiceSchedule__c-Service Schedule Layout.layout-meta.xml
- force-app/main/default/lwc/futureSessionDeleter/futureSessionDeleter.html
- force-app/main/default/lwc/participantAdder/participantAdder.html
- force-app/main/default/lwc/participantAdder/participantAdder.js
- force-app/main/default/lwc/participantAdder/participantAdder.js-meta.xml
- force-app/main/default/lwc/participantSelector/participantSelector.css
- force-app/main/default/lwc/participantSelector/participantSelector.js
- force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
- force-app/main/default/quickActions/ServiceSchedule__c.Add_More_Participants.quickAction-meta.xml
- Add a quick action to Service Schedule to fire the Add Participants component.
> 'Add More Participants' quick action

- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen4.robot
1. Added test to validate message on screen 4 when no service session and service participants are added.
W-8515142
> [Robot] Create service session checkbox on wizard

- force-app/main/default/classes/PermissionValidator.cls
- force-app/main/default/classes/PermissionValidator_TEST.cls
- force-app/main/default/classes/ServiceScheduleCreatorController.cls
- force-app/main/default/classes/ServiceScheduleCreatorController_TEST.cls
- force-app/main/default/classes/ServiceScheduleService.cls
- force-app/main/default/classes/ServiceScheduleService_TEST.cls
- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/participantAdder/participantAdder.html
- force-app/main/default/lwc/participantAdder/participantAdder.js
- 'Add More Participants' quick action will display a warning if the user doesn't have necessary CRUD and FLS.
ServiceSchedule__c - READ
ProgramEngagement__c - READ
ServiceParticipant__c - CREATE
FLS Read access:
ServiceSchedule__c.Service__c,
ServiceSchedule__c.Name,
ProgramEngagement__c.Contact__c,
Contact.Name
FLS Edit access:
ServiceParticipant__c.Name,
ServiceParticipant__c.ServiceSchedule__c,
ServiceParticipant__c.Service__c,
ServiceParticipant__c.ProgramEngagement__c,
ServiceParticipant__c.Contact__c
> Check CRUD and FLS before displaying Add More Participants quick action modal

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/attendance/attendance.html
- force-app/main/default/lwc/attendance/attendance.js
- force-app/main/default/lwc/attendanceRow/attendanceRow.js
- force-app/main/default/lwc/recentSessions/recentSessions.html
- force-app/main/default/lwc/recentSessions/recentSessions.js
- force-app/main/default/objects/ServiceSession__c/listViews/All.listView-meta.xml
> Tweaks from Sprint Review

- cumulusci.yml
- force-app/main/default/classes/Util.cls
- unpackaged/users/rosa.json
> Add cause to error message; easily create Rosa user

- force-app/main/default/flexipages/Program_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Service_Record_Page.flexipage-meta.xml
Removed the report charts from Program and Service flexi pages
~~- [ ] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage  ~~
> Remove report charts from flexi pages

- robot/pmm/tests/browser/Attendance/empty_attendance.robot
> Robot: Empty state on Track Attendance component

- robot/pmm/tests/browser/ProgramEngagement/autopopulate_pe_fields.robot
W-8746330 - Auto populate field when PE stage is Active 
- Program Engagement - Auto-populate field when program start date is later than today and stage is 'Active'
- Program Engagement - Auto-populate field when program start date is today and stage is 'Active'
- Program Engagement - Auto-populate field when program start date is earlier than today and stage is 'Active'
> [Robot] updated auto-populate tests on PE

- force-app/main/default/objects/ProgramEngagement__c/fields/Stage__c.field-meta.xml
Modified the existing description of stage field on program engagement to the following so subscriber's don't change the API name of the picklist values :
A Contact's Stage in a Program Engagement. Picklist values are determined by your admin. Don't delete or modify the API Name of the Active and Enrolled picklist values as they are referenced in PMM reports.
~~- [ ] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage  ~~
> Update description of stage field on program engagement

- force-app/main/default/classes/FeatureParameters.cls
- force-app/main/default/classes/FeatureParameters_TEST.cls
- force-app/main/default/classes/ServiceScheduleService_TEST.cls
- force-app/main/default/classes/TestDataFactory.cls
- force-app/main/default/featureParameters/AttendanceServiceDeliveriesLast30.featureParameterInteger-meta.xml
We have added a new featureParameter called AttendanceServiceDeliveriesLast30Days which gives a count of service deliveries created in the last 30 days where Attendance Status is not null. This new feature will not affect the customers. 
~~- [ ] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage ~~
> Attendance Status/Service Delivery records created in last 30 days

- robot/pmm/resources/locators_49.py
- robot/pmm/resources/locators_50.py
- robot/pmm/tests/browser/Attendance/dim_attendance.robot
- robot/pmm/tests/browser/Attendance/empty_attendance.robot
- robot/pmm/tests/browser/Attendance/update_attendance.robot
- robot/pmm/tests/browser/Bulk_Service_Delivery/Add_service_deliveries.robot
- robot/pmm/tests/browser/Bulk_Service_Delivery/add_pe_on_BSDT.robot
- robot/pmm/tests/browser/Contact/create_contact.robot
- robot/pmm/tests/browser/Contact/quickactions.robot
- robot/pmm/tests/browser/Program/add_service.robot
- robot/pmm/tests/browser/Program/create_program.robot
- robot/pmm/tests/browser/Program/pe_quickaction.robot
- robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
- robot/pmm/tests/browser/ProgramEngagement/ProgramEngagement.robot
- robot/pmm/tests/browser/ProgramEngagement/autopopulate_pe_fields.robot
- robot/pmm/tests/browser/ProgramEngagement/quick_actions_sd.robot
- robot/pmm/tests/browser/Service/new_service.robot
- robot/pmm/tests/browser/Service/quickactions_service.robot
- robot/pmm/tests/browser/ServiceDeliveries/new_service_delivery.robot
- robot/pmm/tests/browser/ServiceParticipant/new_service_participant.robot
- robot/pmm/tests/browser/ServiceSchedule/new_service_schedule.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen2.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen4.robot
- robot/pmm/tests/browser/ServiceSchedule/view_perms_layout.robot
- robot/pmm/tests/browser/ServiceSession/new_service_session.robot
1. Enable test for non admin users
2. Added test for View Perm set: Add More Service Participants quick action
> [Robot] Enable robot tests for non admin users

- force-app/main/default/classes/AttendanceService_TEST.cls
- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
- force-app/main/default/lwc/serviceDeliveryModal/serviceDeliveryModal.html
- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
You can now save any additions or edits to your Bulk Service Deliveries with a Save button, versus previous auto-save functionality. If a row can't save, you're prompted to edit and save them again. You can also edit saved rows at any time. 
> BSDT Manual Save

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/participantSelector/participantSelector.html
- force-app/main/default/lwc/participantSelector/participantSelector.js
- When you select participants in the New Service Schedule wizard, you can now use an "Add" button on each row to add participants with a single click. We also added a new "Add All" button.
> Add/Add All buttons for Participant Selector

- robot/pmm/doc/Keywords.html
- robot/pmm/resources/HomePageObject.py
- robot/pmm/resources/locators_51.py
- robot/pmm/resources/pmm.py
- robot/pmm/tests/browser/Attendance/dim_attendance.robot
- robot/pmm/tests/browser/Bulk_Service_Delivery/Add_service_deliveries.robot
- robot/pmm/tests/browser/Bulk_Service_Delivery/add_pe_on_BSDT.robot
- robot/pmm/tests/browser/HomePage/homepage_components.robot
- robot/pmm/tests/browser/HomePage/homepage_reports.robot
- robot/pmm/tests/browser/ServiceSchedule/new_service_schedule.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
W-8956949
Validates the following are displayed on homepage:
1. Clients with missing phone number report
2. All Active Program Engagements report
3. Services delivered (year to date) report
4. Recent Items component
5. Today's Tasks component
Also updated:
- 'Select Value From Dropdown' keyword and related locator to fix failing Program Engagement tests
- BSDT and Service Schedule tests labeled unstable while those components are being modified
> [Robot] Added tests for PMM homepage

- robot/pmm/tests/browser/Program/create_program.robot
- robot/pmm/tests/browser/ServiceDeliveries/sd_quickaction.robot
[W-9056626](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH0000009ALyYAM/view) Program - View listview
[W-9057513](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH0000009BPUYA2/view) Service Delivery - Create new SD using quick action
> [Robot] Verify Programs listview, create new SD using quick action button

- force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
Fixes an issue where the default service quantity wasn't being maintained if the user went back and reset information in step 1 of the Service Schedule Wizard.
[W-8939893](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000097YfvIAE/view)
> Reset Default Service Quantity in Schedule Wizard

- robot/pmm/doc/Keywords.html
- robot/pmm/resources/ServiceSchedulePageObject.py
- robot/pmm/resources/locators_51.py
- robot/pmm/tests/browser/ServiceSchedule/new_service_schedule.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
Updates to existing robot tests for the new Add Participants page on the Service Schedule wizard
> [Robot] Updates to existing Service Schedule tests

- force-app/main/default/lwc/attendance/attendance.js-meta.xml
Added design properties to expose the attendance component to experience cloud. When the customer goes to the experience cloud builder to build the community they will be able to see the attendance component in the list of components.
~~- [] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage ~~
> Exposing attendance component to experience cloud

- package.json
- yarn.lock
Fixes a dependabot notification on is-svg
No Release Notes Required
> dependabot fix

- force-app/main/default/classes/ServiceDeliveryController.cls
- force-app/main/default/classes/ServiceDeliveryController_TEST.cls
- force-app/main/default/classes/ServiceService.cls
- force-app/main/default/classes/ServiceService_TEST.cls
- force-app/main/default/classes/Stub.cls
- force-app/main/default/classes/Stub.cls-meta.xml
- force-app/main/default/classes/StubBuilder.cls
- force-app/main/default/classes/StubBuilder.cls-meta.xml
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
If the service field does not exist on the BSDT fieldsets then we will be automatically adding the field to the UI.
~~- [ ] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage ~~
> BSDT fieldset changes

- force-app/main/default/layouts/ProgramEngagement__c-Program Engagement Layout.layout-meta.xml
- force-app/main/default/objects/ProgramEngagement__c/fields/Role__c.field-meta.xml
- force-app/main/default/objects/ProgramEngagement__c/fields/Stage__c.field-meta.xml
- force-app/main/default/quickActions/Contact.AddContactToProgram.quickAction-meta.xml
- force-app/main/default/quickActions/Program__c.AddContactToProgram.quickAction-meta.xml
- The Stage and Role fields are no longer required on Program Engagement. Existing customers who want these fields to behave as not-required will need to make that adjustment to the Program Engagement page layout and the "Add Contact to Program" quick actions on Contact and Program.
> PE fields no longer required

- force-app/main/default/lwc/recentSessions/recentSessions.js
Fixes the count for the number of recent sessions per day on the Recent Sessions component.
[W-9222936
](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000KuQSYA0/view)
> Fix for count calculation on Recent Sessions

- force-app/main/default/aura/createServiceSchedule/createServiceSchedule.cmp
- force-app/main/default/aura/createServiceSchedule/createServiceScheduleController.js
- force-app/main/default/classes/FieldSetService.cls
- force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
- force-app/main/default/lwc/serviceScheduleCreator/__tests__/serviceScheduleCreator.test.js
- force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
- force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
- force-app/main/default/lwc/serviceScheduleCreatorWrapper/__tests__/serviceScheduleCreatorWrapper.test.js
- force-app/main/default/lwc/serviceScheduleCreatorWrapper/serviceScheduleCreatorWrapper.html
- force-app/main/default/lwc/serviceScheduleCreatorWrapper/serviceScheduleCreatorWrapper.js
- force-app/main/default/lwc/serviceScheduleCreatorWrapper/serviceScheduleCreatorWrapper.js-meta.xml
- The custom wizard override for creating a new Service Schedule now works in Experience Cloud.
- ~~CRUD/FLS is enforced in Apex~~
- ~~Permission sets are updated to account for CRUD|FLS|Tab|Classes~~
- ~~Field sets are updated to account for new fields~~
> Make New Service Schedule work in Experience Cloud

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/attendance/attendance.html
- force-app/main/default/lwc/attendance/attendance.js
Adds a message to the attendance tab to let users know the tab shouldn't be used directly
[W-9049173](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH00000091SgYAI/view)
> Add empty state warning to Attendance tab when no recordId

- force-app/main/default/reports/ProgramManagementReports/Contacts_Absent_for_Last_Svc_Delivery_qwd.report-meta.xml
- force-app/main/default/reports/ProgramManagementReports/Contacts_with_3_Consecutive_Absences_p3K.report-meta.xml
Added a new summary level field to Contacts with 3 Consecutive Absences and Contacts Absent for Last Svc Delivery
on PMM so it displays this unique count on the caseman dashboard.
> Displaying unique contact count on caseman dashboard

- cumulusci.yml
Create hidden plan in metadeploy for upgrade installation.
> [PMM] Upgrade metadeploy install plan

- force-app/main/default/classes/ServiceDeliverySelector.cls
- force-app/main/default/classes/ServiceDeliveryService.cls
- force-app/main/default/classes/ServiceDeliveryService_TEST.cls
No work item / pr notes: quick fix for 2gp orgs and namespace issue.
> Fix bucket namespace, separate field not part of devName

- force-app/main/default/classes/ProgramEngagementSelector.cls
- force-app/main/default/classes/ServiceScheduleService.cls
- force-app/main/default/lwc/loadingStencil/__tests__/loadingStencil.test.js
- force-app/main/default/lwc/loadingStencil/loadingStencil.css
- force-app/main/default/lwc/loadingStencil/loadingStencil.html
- force-app/main/default/lwc/loadingStencil/loadingStencil.js
- force-app/main/default/lwc/loadingStencil/loadingStencil.js-meta.xml
- force-app/main/default/lwc/participantSelector/participantSelector.html
- force-app/main/default/lwc/participantSelector/participantSelector.js
- force-app/main/default/lwc/picklist/picklist.js
- On Bulk Service Delivery Wizard and the Service Schedule Wizard, the participant/contact selector screen will now present a larger amount of data up to the maximum number rows allowed by SOQL.
- On Service Schedule Wizard when in Lightning Debug Mode there is no longer a console error and the Frequency options load.
- Fixes #433 
> Fix error on Service Schedule Wizard when in Lightning Debug Mode and Fix error when attempting to load more than 50000 related Program Engagements

- force-app/main/default/classes/FeatureParameters.cls
- force-app/main/default/classes/FeatureParameters_TEST.cls
- Fixes an issue where the name of a telemetry feature parameter was incorrect and could not be sent.
> Fix name of attendance feature parameter.

- force-app/main/default/classes/FeatureParameters.cls
- force-app/main/default/classes/FeatureParameters_TEST.cls
- force-app/main/default/classes/ServiceDeliveryRollupsService.cls
- force-app/main/default/classes/Util.cls
- Fixes an issue where a customer could hit too many query row limit if they have more than 50000 Service Deliveries created in the last 30 days.
> Reduce the number of query rows needed for telemetry

- force-app/main/default/classes/FeatureParameters.cls
- force-app/main/default/classes/FeatureParameters_TEST.cls
- force-app/main/default/featureParameters/ActiveServices.featureParameterInteger-meta.xml
- New telemetry query to send us how many active services an org has.
> Add active services telemetry

- force-app/main/default/classes/FeatureParameters.cls
- force-app/main/default/classes/FeatureParameters_TEST.cls
- force-app/main/default/classes/TestDataFactory.cls
- force-app/main/default/featureParameters/ActiveServicesWithServiceSchedules.featureParameterInteger-meta.xml
We added Feature Telemetry to track the number of active Services with Service Schedules.
> Telemetry for active services with service schedules

- force-app/main/default/lwc/participantSelector/participantSelector.js
Filtering out the availableRows array before adding the deselected value to avoid duplicate values
> Removing duplicate entries in participant selector

- force-app/main/default/classes/AttendanceController.cls
- force-app/main/default/classes/AttendanceController_TEST.cls
- force-app/main/default/classes/FieldSetService.cls
- force-app/main/default/classes/ServiceDeliverySelector.cls
- force-app/main/default/classes/ServiceDeliverySelector_TEST.cls
- force-app/main/default/classes/ServiceDeliveryService.cls
- force-app/main/default/classes/ServiceDeliveryService_TEST.cls
- force-app/main/default/classes/TestStub.cls
- force-app/main/default/layouts/Service__c-Service Layout.layout-meta.xml
- force-app/main/default/lwc/attendance/__tests__/attendance.test.js
- force-app/main/default/lwc/attendance/__tests__/data/emptyRoster.json
- force-app/main/default/lwc/attendance/__tests__/data/generateRoster.json
- force-app/main/default/lwc/attendance/attendance.js
- force-app/main/default/objects/Service__c/fields/AttendanceFieldSet__c.field-meta.xml
- force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
- A new field, AttendanceFieldSet__c, was added to the Service Object
- This new field will drive the fields that are displayed on the Attendance component on a Service Session record
- When no value is present we will continue to use the default Attendance_Service_Delivery field set
> Dynamic fields displayed on Attendance UI based on Field Set

- force-app/main/default/classes/FieldSetService.cls
- force-app/main/default/classes/FieldSetService_TEST.cls
Changing how related object name fields are discovered
In FieldSetService, when retrieving fields for a field set (or other purposes), when preparing the data structure that contains details about a particular field, if a lookup field is being represented the referenced object name and the name of the field on the referenced object that represents the name of the referenced object is determined and included in the returned data structure representing the lookup field.
The way determination of the name field of a referenced object was being done was to issue a SOQL query against the FieldDefinition table.  However, when many fieldsets are being processed, this was causing this SOQL query to be run for every lookup field that was included.  In some cases, this was causing an exception in …
> W-10433201 - Fix "too many queries" error for field set discovery

- package.json
- yarn.lock
Updating package.json to add a dependency resolution override to choose to use versions of pretty-format compatible with version 25.5.0, and versions of strip-ansi compatible with 6.0.0.
> Adding version overrides for vulnerable dependencies

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/attendance/attendance.js
- force-app/main/default/lwc/attendanceRow/attendanceRow.html
- force-app/main/default/staticresources/pmm/attendancePrintOverride.css
Updates the Service Delivery rows in the Attendance component to handle a greater number of fields.  
Fixes a situation where the fields are displayed unevenly when labels are on two lines.
[W-10398948](https://gus.lightning.force.com/a07EE00000dJnxwYAC)
> Attendance Component Row UI Enhancement

- force-app/main/default/classes/AttendanceController.cls
- force-app/main/default/classes/AttendanceController_TEST.cls
- force-app/main/default/classes/ServiceDeliverySelector.cls
- force-app/main/default/classes/ServiceDeliveryService.cls
- force-app/main/default/classes/ServiceDeliveryService_TEST.cls
- force-app/main/default/lwc/attendance/attendance.js
- force-app/main/default/lwc/attendance/attendance.js-meta.xml
This work adds design properties to the attendance tracker component (visible on the service session page) to allow admins to filter untracked participants by the Status of Service Participant and Role or Stage of the Program Engagement related to the record. If no filters are specified (what customers will experience at the time this feature is released) than no filtering is applied, meaning that the customer experience should be unchanged until they chose to apply filters. 
- [W-9655326](https://gus.lightning.force.com/a07AH000000SBNjYAO)
- ~[] Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage~
- ~[ ] Permission sets are updated to …
> Filter Service Participants that show up on Track Attendance by status, role and stage

- force-app/main/default/classes/AttendanceController.cls
- force-app/main/default/classes/AttendanceController_TEST.cls
- force-app/main/default/classes/RecentServiceSessionController.cls
- force-app/main/default/classes/RecentServiceSessionController_TEST.cls
- force-app/main/default/classes/ServiceDeliveryService.cls
- force-app/main/default/classes/ServiceSessionSelector.cls
- force-app/main/default/classes/ServiceSessionService.cls
- force-app/main/default/classes/ServiceSessionService_TEST.cls
- force-app/main/default/customMetadata/Bucket.Complete.md-meta.xml
- force-app/main/default/customMetadata/Bucket.Pending.md-meta.xml
- force-app/main/default/customMetadata/BucketedField.ServiceSessionStatuses.md-meta.xml
- force-app/main/default/customMetadata/BucketedValue.Complete.md-meta.xml
- force-app/main/default/customMetadata/BucketedValue.Pending.md-meta.xml
- force-app/main/default/lwc/attendance/__tests__/attendance.test.js
- force-app/main/default/lwc/attendance/__tests__/data/wiredGetSessionStatuses.json
- force-app/main/default/lwc/attendance/attendance.js
- force-app/main/default/lwc/recentSessions/recentSessions.html
- force-app/main/default/lwc/recentSessions/recentSessions.js
- force-app/main/default/lwc/sessionCard/sessionCard.js
Created a new Bucketed Field metadata for service session status
Created 2 new buckets to represent the service session status. The two new buckets are Pending and Complete
Now the recent sessions component will be driven off of the bucket fields. Any status value under the Complete bucket will show up with a green checkmark on the component
If there is a status that is not part of any of the buckets then that status will not show up on the recent service session component
The attendance component is also driven off of the bucket values. Any status value under the Complete bucket will put the component in read only mode with an update button
Any status under the Pending bucket will put the attendance component in edit mode and the users will see the submit button.
Refer to [Asteroids DoD …
> Add buckets for service sessions

- .github/workflows/codeowners.yml
Triggers user mentions when a PR requires CODEOWNERS review from Release Engineering.
> Add SFDO Codeowners workflow

- force-app/main/default/classes/ServiceScheduleModel.cls
- force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
Fixes missing and incorrect labels on the Service Schedule Wizard progress bar.
[W-10311109](https://gus.lightning.force.com/a07EE00000XtqtFYAR)
[W-10311100](https://gus.lightning.force.com/a07EE00000Xtqt6YAB)
> Service Schedule Progress Bar Labels

- robot/pmm/resources/locators_52.py
- robot/pmm/resources/pmm.py
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
To resolve the NoErrorObjectAvailable error when running the SSL1: Add Service Participant quick action robot test , updated the locator for the Save button on the Add Service Participant modal. This modal will be displayed when the Add Service Participant button is clicked on the Service Schedule page layout.
To run the individual test run the below command in the terminal:
`cci task run robot -o test 'SSL1: Add Service Participant quick action'`
[W-10981883](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000umbVfYAI/view) …
> Updated the locator for the Add Service participant modal save button

- force-app/main/default/lwc/modal/modal.html
Increases the color contrast when the modal's close button is focused.  Aligns with core.
[W-10311112](https://gus.lightning.force.com/a07EE00000XtqtIYAR)
> Modal Close A11y Contrast

- force-app/main/default/classes/FieldSetService.cls
- force-app/main/default/classes/FieldSetService_TEST.cls
- force-app/main/default/lwc/attendanceRow/attendanceRow.js
- force-app/main/default/lwc/formattedField/formattedField.js
- force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
- force-app/main/default/lwc/participantSelector/participantSelector.js
- force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.html
- force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.js
- force-app/main/default/lwc/util/util.js
- Fields of type Time were previously not supported on Lightning Record components. Now that it is we will also allow the usage on our custom components. The time field is not fully supported in Lightning Datatable and will display in a raw time format.
> Allow fields of type Time to be used in Components surfacing field set fields

- force-app/main/default/classes/ServiceParticipantRollupsService.cls
- force-app/main/default/classes/ServiceParticipantRollupsService.cls-meta.xml
- force-app/main/default/classes/ServiceParticipantRollupsService_TEST.cls
- force-app/main/default/classes/ServiceParticipantRollupsService_TEST.cls-meta.xml
- force-app/main/default/classes/ServiceParticipantTriggerHandler.cls
- force-app/main/default/classes/ServiceParticipantTriggerHandler.cls-meta.xml
- force-app/main/default/classes/ServiceParticipantTriggerHandler_TEST.cls
- force-app/main/default/classes/ServiceParticipantTriggerHandler_TEST.cls-meta.xml
- force-app/main/default/classes/ServiceScheduleSelector.cls
- force-app/main/default/classes/ServiceScheduleSelector_TEST.cls
- force-app/main/default/classes/TestUtil.cls
- force-app/main/default/customMetadata/FeatureGate.ServiceParticipantsToServiceSchedule.md-meta.xml
- force-app/main/default/layouts/ServiceSchedule__c-Service Schedule Layout.layout-meta.xml
- force-app/main/default/objects/ServiceSchedule__c/fields/ParticipantsEnrolled__c.field-meta.xml
- force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
- force-app/main/default/triggers/ServiceParticipantTrigger.trigger
- force-app/main/default/triggers/ServiceParticipantTrigger.trigger-meta.xml
Created a new field called ParticipantsEnrolled on ServiceSchedule object also added help text to the field
Created a new feature gate record which will be shipped as Inactive
Modified the permission sets so users cannot edit the field
Added this field to ServiceSchedule page layout just below Participant Capacity field
Added a new trigger on the Service Participant object to roll up the number of participants whose status is set to enrolled
[W-10999445](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000utl7LYAQ/view)
Participants Enrolled field on Service Schedule object
~~- [ ] Any net new LWC work has Sa11y tests & 50% or above lines JEST test …
>  Participant rollup on ServiceSchedule

- force-app/main/default/lwc/modal/modal.html
- force-app/main/default/lwc/modal/modal.js
- When a custom component opens a modal, the focus will default to the modal header. In situations where the modal is used to override new like in Service Schedules and the user refreshes the page the focus will be reset to the very beginning of the page see [Page Loads and Refreshes](https://www.lightningdesignsystem.com/accessibility/guidelines/global-focus/#page-loads-refreshes).
> Give Modal Heading Default Focus on Open

- force-app/main/default/aura/deleteServiceDeliveries/deleteServiceDeliveries.cmp
- force-app/main/default/aura/deleteServiceDeliveries/deleteServiceDeliveries.cmp-meta.xml
- force-app/main/default/aura/deleteServiceDeliveries/deleteServiceDeliveriesController.js
- force-app/main/default/classes/ServiceDeliveryController.cls
- force-app/main/default/classes/ServiceDeliveryController_TEST.cls
- force-app/main/default/classes/ServiceDeliveryDomain.cls
- force-app/main/default/classes/ServiceDeliveryDomain_TEST.cls
- force-app/main/default/classes/ServiceDeliverySelector.cls
- force-app/main/default/classes/ServiceDeliverySelector_TEST.cls
- force-app/main/default/flexipages/Service_Schedule_Record_Page.flexipage-meta.xml
- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/layouts/ServiceSession__c-Service Session Layout.layout-meta.xml
- force-app/main/default/lwc/serviceDeliveryDeleter/serviceDeliveryDeleter.html
- force-app/main/default/lwc/serviceDeliveryDeleter/serviceDeliveryDeleter.js
- force-app/main/default/lwc/serviceDeliveryDeleter/serviceDeliveryDeleter.js-meta.xml
- force-app/main/default/quickActions/ServiceSession__c.Delete_All_Service_Deliveries.quickAction-meta.xml
> W-10999493: Option to delete all service deliveries on a service session

- force-app/main/default/lwc/participantAdder/participantAdder.js
When the user clicks the Add participants quick action on the service schedule page layout and if the number of participants added is more than the Participant Capacity then the user sees a warning on the Add Selector screen.
[W-11195802](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000xjAMvYAM/view)
> Display Capacity warning

- scripts/Delete_PMM_PSL_Assignments_Rosa.apex
// Internal script for use with cci to easily switch Rosa's permission set assignments.
> Script to delete Rosa's PSA.

- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
Added aria label and aria live to service delivery row html file so when there is an error message, the message is announced to the user. We now will show an error message if program engagement field is not filled in.
[W-10241719](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000U1v8jYAB/view)
[W-10241720](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000U1v8kYAB/view)
~~- [ …
> Announce error message via screen reader

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/participantSelector/participantSelector.js
- force-app/main/default/lwc/reviewSessions/reviewSessions.js
Adds labels to the previously empty datatable column headings
[W-10311059](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000XtelEYAR/view)
> Action Column Labels for DataTable

- force-app/main/default/lwc/picklist/picklist.html
- force-app/main/default/lwc/picklist/picklist.js
With this change now the screen reader announces which day of the week is selected.
[W-10311101](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000Xtqt7YAB/view)
> Screen readers announcing the day of the week selected

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.html
- force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.js
- Added error banner for Service Delivery Defaults in Group Option of Bulk Service Delivery Tool
> WIP: Added error banner for Service Delivery Defaults in BSDT

- force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
// When the Add More Sessions button is clicked on an existing session, and the monthly option is selected, the picklist defaults to the start date. This feature has not yet been released so no release notes are needed.
[W-11418571](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000011ILZ0YAO/view)
> Fix Monthly Schedule

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
Update markup to correctly announce save and error messages on row-level save of BSDT
- [W-10311123](https://gus.lightning.force.com/a07EE00000XtqtTYAR)
> W-10311123: [Accessibility] The “Saved” and “Error” status alert notifications are not detected and announced by the assistive tech

- force-app/main/default/applications/Program_Management.app-meta.xml
- force-app/main/default/flexipages/Service_Schedule_Record_Page.flexipage-meta.xml
Adds configuration for the Service Schedule flexipage to have mobile appropriate quick actions.
> Dynamic actions for Service Schedule page

- force-app/main/default/classes/ProgramEngagementSelector.cls
- force-app/main/default/classes/ProgramEngagementSelector_TEST.cls
- force-app/main/default/classes/ProgramEngagementService.cls
- force-app/main/default/classes/ProgramEngagementService_TEST.cls
- force-app/main/default/classes/SelectParticipantModel.cls
- force-app/main/default/classes/ServiceScheduleCreatorController.cls
- force-app/main/default/classes/ServiceScheduleCreatorController_TEST.cls
- force-app/main/default/classes/ServiceScheduleService.cls
- force-app/main/default/classes/ServiceScheduleService_TEST.cls
- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/participantSelector/participantSelector.html
- force-app/main/default/lwc/participantSelector/participantSelector.js
Adds a Stage Filter to the Participant Selector component
> Stage Filter for Participant Selector

- force-app/main/default/classes/ProgramEngagementSelector.cls
- force-app/main/default/classes/ProgramSelector.cls
- force-app/main/default/classes/ServiceSelector.cls
Adds ORDER BY clauses for apex methods returning records for BSDT comboboxes.
- Cohorts
- Program Engagements
- Services
> Sort order for BSDT Comboboxes

- cumulusci.yml
Related WI: [W-12674462](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001Mz9NwYAJ/view)
Related TD: [TD-0127818](https://gus.lightning.force.com/lightning/r/a0nEE0000008Y2vYAE/view)
Update cumulusci.yml to use static release notes (instead of dynamic-generated ones) that redirect to the H&T SFDO release notes
> W-12674462 - Update cumulusci.yml for static release notes

- .gitignore
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
- force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
* Debounce BSDT Save Button [[PR673](https://github.com/SalesforceFoundation/PMM/pull/673)]
* Service Schedule Modal Error [[PR674](https://github.com/SalesforceFoundation/PMM/pull/674)]
> FEATURE 248 BRANCH

- force-app/main/default/classes/ServiceDeliveryController.cls
- force-app/main/default/classes/ServiceDeliveryController_TEST.cls
- force-app/main/default/classes/ServiceDeliveryDomain.cls
- force-app/main/default/classes/ServiceDeliveryDomain_TEST.cls
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
- force-app/main/default/lwc/util/util.js
- Fixes an issue where Bulk Service Delivery rollups caused a row lock error.
> Move to bulk save.
