- .forceignore
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
Fix for incorrect done button title on BSDT interface.
> Fix for incorrect done button title

- data/bulk/data.sql
- force-app/main/default/objects/ProgramEngagement__c/fields/Program__c.field-meta.xml
- force-app/main/default/objects/ProgramEngagement__c/validationRules/ACCOUNT_MATCHES_CONTACT_ACCOUNT.validationRule-meta.xml
- force-app/main/default/objects/ProgramEngagement__c/validationRules/PROGRAM_MATCHES_COHORT_PROGRAM.validationRule-meta.xml
- force-app/main/default/objects/ServiceDelivery__c/validationRules/ACCOUNT_MATCHES_CONTACT_ACCOUNT.validationRule-meta.xml
- force-app/main/default/objects/ServiceDelivery__c/validationRules/PROGRAM_MATCH.validationRule-meta.xml
> Add validation rules

- cumulusci.yml
> Pin to SFDO Base 1.0

- force-app/main/default/layouts/ProgramEngagement__c-Program Engagement Layout.layout-meta.xml
- Added the files related list below the service delivery related list on program engagement page layout.
> Files related list on program enagagement

- data/bulk/data.sql
- Modified the sql file to fix the issue with incorrect program cohort on 3 program engagement records.
~~- [ ] PR contains draft release notes~~
> Fix program cohort on program engagement records

- robot/pmm/doc/Keywords.html
- robot/pmm/resources/ProgramCohortPageObject.py
- robot/pmm/resources/pmm.py
- robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
1. Added date validation for program cohort
2. Updated create new program cohort test - to create the record from the listing page and not from the program page
> added date validation for cohort

- force-app/main/default/objects/ProgramEngagement__c/fieldSets/CreateProgramEngagement.fieldSet-meta.xml
- We modified the Program Engagement field set: the Client field is no longer required.
> Remove client as required field from program engagement fieldset

- unpackaged/post/reports/reports/ProgramManagementReportsUnpackaged/Service_Deliveries_by_Provider_LastMonth_PEO.report
> Update unpackaged report chart

- force-app/main/default/classes/FieldSetService.cls
- force-app/main/default/classes/FieldSetService_TEST.cls
- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
- force-app/main/default/objects/ServiceDelivery__c/fieldSets/Default.fieldSet-meta.xml
~~Permission sets are updated to account for CRUD/FLS for new object metadata~~
> Special handling of various field types

- .forceignore
- cumulusci.yml
~~Permission sets are updated to account for CRUD/FLS for new object metadata~~
~~All modified classes are unit tested (Apex) at 100% coverage~~
~~Attach work item to the pull request with [Lurch](https://salesforce.quip.com/50ZRA5LEWVzH) `**Lurch:attach W-000000` or `**Lurch:add`~~
~~QE story level testing completed~~
> Handle namespace injection in packaging org

- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
- force-app/main/default/objects/ServiceDelivery__c/fieldSets/Bulk_Service_Deliveries.fieldSet-meta.xml
Changed fieldset name on service delivery from 'Default' to  'Bulk Service Deliveries'
> Changed fieldset name on service delivery

- robot/pmm/doc/Keywords.html
- robot/pmm/resources/pmm.py
- robot/pmm/resources/pmm_locators.py
- robot/pmm/tests/browser/Contact/create_contact.robot
- robot/pmm/tests/browser/Program/pe_quickaction.robot
- robot/pmm/tests/browser/ProgramEngagement/quick_actions_sd.robot
- robot/pmm/tests/browser/ServiceDeliveries/new_service_delivery.robot
1. Added test to validate cohort and PE lookup to same program
2. Fixed verify details keyword
3. Updated locators
W-042769
> [Robot] Test to validate cohort and PE lookup to same program

- force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml
- force-app/main/default/reports/ProgramManagementReports/All_Active_Program_Engagements_HWv.report-meta.xml
- force-app/main/default/reports/ProgramManagementReports/Client_Records_with_Missing_Phone_Number.report-meta.xml
- force-app/main/default/reports/ProgramManagementReports/Clients_Enrolled_This_Month_6ez.report-meta.xml
- force-app/main/default/reports/ProgramManagementReports/Clients_Enrolled_This_Month_by_Program_Nk9.report-meta.xml
- force-app/main/default/reports/ProgramManagementReports/Services_Delivered_Year_to_Date_MY.report-meta.xml
- force-app/main/default/reports/ProgramManagementReports/Units_Delivered_over_last_6_Months_3DR.report-meta.xml
- We renamed the Contact Record Page label Program Management Contact Record.
- We updated report descriptions on packaged reports to describe the question the report answers and where the report is used in PMM.
<s>Place holder data is incorporated (Refer to [Case Management Sample Data document](https://quip.com/cbFcAPJF8t0z))
Base axe-core JEST test included for any new LWC (No critical violations)
CRUD/FLS is enforced in Apex
Permission sets are updated to account for CRUD/FLS for new object metadata
All modified classes are unit tested (Apex) at 100% coverage</s>
> Update report descriptions and flexipage label

- unpackaged/post/reports/reports/ProgramManagementReportsUnpackaged/Enrolled_Active_Prog_Eng_by_Owner_JZY.report
Internal fix for unpackaged reports.
> Add namespace token to new unpackaged report

- unpackaged/post/reports/reports/ProgramManagementReportsUnpackaged/Enrolled_Active_Prog_Eng_by_Owner_JZY.report
// Internal fix to unpackaged report
> Remove the language setting from the report filter

- cumulusci.yml
- metadeploy/labels_en.json
- Added a new installer plan to deliver unpackaged reports to existing customers.
> Add installer

- .github/PULL_REQUEST_TEMPLATE.md
Updated our DoD for Testing Permission for new features and CRUS/FLS
> Updated our DoD for Testing Permission Sets

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/reviewSessions/reviewSessions.html
- force-app/main/default/lwc/reviewSessions/reviewSessions.js
- force-app/main/default/lwc/reviewSessions/reviewSessions.js-meta.xml
- force-app/main/default/lwc/util/util.js
- The Review Sessions component will be used in the wizard that will display the sessions that will be created 
- Created a couple of labels that will be consumed by the component
NOTE : For testing purposes this LWC component is exposed. Once testing is complete will be turning that off.
~~- [ ] All modified classes are unit tested (Apex) at …
> Review sessions component

- force-app/main/default/flexipages/Service_Participant_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Service_Schedule_Record_Page.flexipage-meta.xml
- force-app/main/default/flexipages/Service_Session_Record_Page.flexipage-meta.xml
> Update winter21 flexipage tags

- force-app/main/default/objects/ServiceSession__c/ServiceSession__c.object-meta.xml
- force-app/main/default/objects/ServiceSession__c/fields/ServiceSchedule__c.field-meta.xml
Updated the Master-Detail relationship from Service Schedule to Service Session to be a lookup.
> Service Schedule to Service Session relationship changed to lookup

- force-app/main/default/layouts/Contact-Program Management.layout-meta.xml
Added Session Participant Related list to PMM Contact Layout
> Adding Participant Related list to Contact Layout

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/objects/ServiceSchedule__c/fields/Interval__c.field-meta.xml
> Add missing Winter21 strings

- force-app/main/default/classes/DailyIterator.cls
- force-app/main/default/classes/DailyIterator_TEST.cls
- force-app/main/default/classes/RecurrenceFactory.cls
- force-app/main/default/classes/RecurrenceFactory_TEST.cls
- force-app/main/default/classes/RecurrenceRule.cls
- force-app/main/default/classes/RecurrenceRule_TEST.cls
- force-app/main/default/classes/RecurrenceService.cls
- force-app/main/default/classes/RecurrenceService_TEST.cls
- force-app/main/default/classes/WeeklyIterator.cls
- force-app/main/default/classes/WeeklyIterator.cls-meta.xml
- force-app/main/default/classes/WeeklyIterator_TEST.cls
- force-app/main/default/classes/WeeklyIterator_TEST.cls-meta.xml
> Recurrence: Weekly Iterator

- force-app/main/default/objectTranslations/ServiceParticipant__c-de/ServiceParticipant__c-de.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceParticipant__c-en_GB/ServiceParticipant__c-en_GB.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceParticipant__c-es/ServiceParticipant__c-es.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceParticipant__c-es_MX/ServiceParticipant__c-es_MX.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceParticipant__c-fr/ServiceParticipant__c-fr.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceParticipant__c-fr_CA/ServiceParticipant__c-fr_CA.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceParticipant__c-ja/ServiceParticipant__c-ja.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceParticipant__c-nl_NL/ServiceParticipant__c-nl_NL.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSchedule__c-de/ServiceSchedule__c-de.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSchedule__c-en_GB/ServiceSchedule__c-en_GB.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSchedule__c-es/ServiceSchedule__c-es.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSchedule__c-es_MX/ServiceSchedule__c-es_MX.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSchedule__c-fr/ServiceSchedule__c-fr.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSchedule__c-fr_CA/ServiceSchedule__c-fr_CA.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSchedule__c-ja/ServiceSchedule__c-ja.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSchedule__c-nl_NL/ServiceSchedule__c-nl_NL.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSession__c-de/ServiceSession__c-de.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSession__c-en_GB/ServiceSession__c-en_GB.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSession__c-es/ServiceSession__c-es.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSession__c-es_MX/ServiceSession__c-es_MX.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSession__c-fr/ServiceSession__c-fr.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSession__c-fr_CA/ServiceSession__c-fr_CA.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSession__c-ja/ServiceSession__c-ja.objectTranslation-meta.xml
- force-app/main/default/objectTranslations/ServiceSession__c-nl_NL/ServiceSession__c-nl_NL.objectTranslation-meta.xml
> Add missing translations

- force-app/main/default/classes/SelectParticipantModel.cls
- force-app/main/default/classes/ServiceScheduleModel.cls
- force-app/main/default/lwc/participantSelector/participantSelector.css
- force-app/main/default/lwc/participantSelector/participantSelector.html
- force-app/main/default/lwc/participantSelector/participantSelector.js
~~Update & Test permission sets to account for new features and CRUD/FLS~~
~~All modified classes are unit tested (Apex) at 100% coverage~~
> Feature/winter 21  capacity warning

- force-app/main/default/classes/ProgramEngagementSelector.cls
~~Update & Test permission sets to account for new features and CRUD/FLS~~
> Use translated label for query of stage

- force-app/main/default/classes/RecurrenceService_TEST.cls
> update tests to accommodate same time post-daylight savings

- force-app/main/default/lwc/reviewSessions/reviewSessions.js
- force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.js
> Increase timeout for spinners

- force-app/main/default/lwc/participantSelector/participantSelector.js
~~Update & Test permission sets to account for new features and CRUD/FLS~~
~~All modified classes are unit tested (Apex) at 100% coverage~~
> Null check

- force-app/main/default/layouts/ServiceDelivery__c-Service Delivery Layout.layout-meta.xml
- force-app/main/default/objects/ServiceDelivery__c/fields/AttendanceStatus__c.field-meta.xml
- force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
- Attendance Status field on Service Delivery
> Add Attendance Status to Service Delivery

- force-app/main/default/layouts/ServiceDelivery__c-Service Delivery Layout.layout-meta.xml
- force-app/main/default/layouts/ServiceSession__c-Service Session Layout.layout-meta.xml
Users will be able to create new Service Delivery records manually from the Service Delivery related list on Service Sessions.
> New button on Service Delivery related list

- robot/pmm/doc/Keywords.html
- robot/pmm/resources/ServiceSessionPageObject.py
- robot/pmm/resources/locators_50.py
- robot/pmm/resources/pmm.py
- robot/pmm/resources/pmm.robot
- robot/pmm/tests/browser/ServiceDeliveries/new_service_delivery.robot
- robot/pmm/tests/browser/ServiceParticipant/new_service_participant.robot
- robot/pmm/tests/browser/ServiceSession/new_service_session.robot
1. Added test to create service session record
2. Updated service delivery test to validate delivery date
W-8294332
> [Robot] Added test to create service session

- .github/PULL_REQUEST_TEMPLATE.md
- force-app/main/default/objects/ServiceDelivery__c/fieldSets/Bulk_Service_Deliveries.fieldSet-meta.xml
Added ServiceSession__c field to BSDT fieldset.
W-8315556
> Add ServiceSession field to available BSDT field set

- force-app/main/default/classes/AttendanceController.cls
- force-app/main/default/classes/AttendanceController_TEST.cls
- force-app/main/default/classes/AttendanceSelector.cls
- force-app/main/default/classes/AttendanceService.cls
- force-app/main/default/classes/AttendanceService_TEST.cls
- force-app/main/default/classes/ServiceDeliveryDomain.cls
- force-app/main/default/classes/ServiceDeliveryDomain.cls-meta.xml
- force-app/main/default/classes/ServiceDeliveryDomain_TEST.cls
- force-app/main/default/classes/ServiceDeliveryDomain_TEST.cls-meta.xml
- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/attendance/attendance.html
- force-app/main/default/lwc/attendance/attendance.js
- force-app/main/default/lwc/attendanceRow/__mocks__/attendanceRow.js
- force-app/main/default/lwc/attendanceRow/attendanceRow.html
- force-app/main/default/lwc/attendanceRow/attendanceRow.js
- Attendance component saves and updates Service Delivery records.
> Attendance Commit

- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
- force-app/main/default/staticresources/pmm/bsdtOverrides.css
- Tightened up spacing of rows in BSDT. (Attendance is handled in the Attendance UI PR.)
> Reduce padding on BSDT row cards

- .forceignore
- force-app/main/default/classes/AttendanceSelector_TEST.cls
- force-app/main/default/classes/AttendanceService_TEST.cls
- force-app/main/default/classes/RecentServiceSessionController.cls
- force-app/main/default/classes/RecentServiceSessionController_TEST.cls
- force-app/main/default/classes/ServiceSessionSelector.cls
- force-app/main/default/classes/ServiceSessionSelector_TEST.cls
- force-app/main/default/classes/ServiceSessionService_TEST.cls
- force-app/main/default/classes/TestDataFactory.cls
- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/accordionSection/accordionSection.css
- force-app/main/default/lwc/recentSessions/recentSessions.css
- force-app/main/default/lwc/recentSessions/recentSessions.html
- force-app/main/default/lwc/recentSessions/recentSessions.js
- force-app/main/default/lwc/sessionCard/sessionCard.html
- force-app/main/default/lwc/sessionCard/sessionCard.js
- force-app/main/default/lwc/sessionCard/sessionCard.js-meta.xml
- force-app/main/default/lwc/skipLinks/skipLinks.css
- force-app/main/default/lwc/skipLinks/skipLinks.html
- force-app/main/default/lwc/skipLinks/skipLinks.js
- force-app/main/default/lwc/skipLinks/skipLinks.js-meta.xml
- force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
- force-app/main/default/staticresources/pmm/recentSessionsOverrides.css
- Moved the individual card to sessionCard component. 
- Added status condition to the ServiceSessionSelector class so we only show Pending and Complete status. 
- Added NavigationMixin so when the sessionName is clicked it takes the user to the 
serviceSession record View page where the attendance component will reside.
> Recent sessions component UI fixes

- robot/pmm/doc/Keywords.html
- robot/pmm/resources/ServicePageObject.py
- robot/pmm/resources/ServiceSchedulePageObject.py
- robot/pmm/resources/locators_50.py
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
1. Updated tests to add/remove service participants
2. Updated service page object file
W-8449817
> [Robot] Add/remove service participants on screen3

- force-app/main/default/lwc/attendanceRow/attendanceRow.js
~~Permission sets & field sets are updated to account for CRUD/FLS/TABS for new object metadata~~
~~All modified classes are unit tested (Apex) at 100% coverage~~
> Handle updates on fields in fieldset

- .github/PULL_REQUEST_TEMPLATE.md
> December 2020 DoD Update

- force-app/main/default/classes/ServiceScheduleService_TEST.cls
> Fix unstable tests using service schedule model wrapper

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/attendanceRow/attendanceRow.html
- force-app/main/default/lwc/attendanceRow/attendanceRow.js
- User can select participants to not create Service Deliveries for in the Attendance component.
- ~~Place holder data is incorporated (Refer to [Case Management Sample Data document](https://quip.com/cbFcAPJF8t0z))~~
- ~~Base axe-core JEST test included for any new LWC (No critical violations)~~
- ~~CRUD/FLS is enforced in Apex~~
- ~~Permission sets & field sets are updated to account for CRUD/FLS/TABS for new object metadata~~
- ~~All modified classes are unit tested (Apex) at 100% coverage~~
> Skip selected participants in Attendance

- force-app/main/default/labels/CustomLabels.labels-meta.xml
Removes a duplicate label definition
> Duplicate Label Fix

- cumulusci.yml
> Try to fix regression_org

- force-app/main/default/classes/ProgramEngagementSelector_TEST.cls
- force-app/main/default/classes/ServiceScheduleService_TEST.cls
- force-app/main/default/classes/ServiceSelector_TEST.cls
- lib/admin_profile.xml
- unencryptable.yml
// Technically no customer facing changes here since everything that was altered was in TEST classes. The field we added to the block list will need to be documented.
~~Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage~~  
> Allow encryption on all possible fields and note when not possible

- robot/pmm/doc/Keywords.html
- robot/pmm/resources/ServiceSchedulePageObject.py
- robot/pmm/resources/ServiceSessionPageObject.py
- robot/pmm/resources/locators_50.py
- robot/pmm/resources/pmm.robot
- robot/pmm/tests/browser/Attendance/dim_attendance.robot
- robot/pmm/tests/browser/Attendance/update_attendance.robot
W-8607484 - Update attendance records when service session status is pending
W-8611541 - Update attendance records when service session status is Complete
W-8613706 -Dim attendance rows
> [Robot] Added test to update attendance records

- package.json
- yarn.lock
> Update Package Versions

- force-app/main/default/objects/ProgramCohort__c/ProgramCohort__c.object-meta.xml
- force-app/main/default/objects/ProgramCohort__c/compactLayouts/ProgramCohortCompactLayout.compactLayout-meta.xml
- force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
- force-app/main/default/objects/ProgramEngagement__c/compactLayouts/ProgramEngagementCompactLayout.compactLayout-meta.xml
- force-app/main/default/objects/Program__c/Program__c.object-meta.xml
- force-app/main/default/objects/Program__c/compactLayouts/ProgramCompactLayout.compactLayout-meta.xml
- force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
- force-app/main/default/objects/ServiceDelivery__c/compactLayouts/ServiceDeliveryCompactLayout.compactLayout-meta.xml
- force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
- force-app/main/default/objects/ServiceSchedule__c/compactLayouts/ServiceScheduleCompactLayout.compactLayout-meta.xml
- force-app/main/default/objects/Service__c/Service__c.object-meta.xml
- force-app/main/default/objects/Service__c/compactLayouts/ServiceCompactLayout.compactLayout-meta.xml
- Updated the Search Layouts on the following objects
- Program Engagements
- Program Cohorts
- Services
- Service Deliveries
- Service Schedules
- Added and assigned Compact Layouts to the following objects
- Program Engagements
- Programs
- Program Cohorts
- Services
- Service Deliveries
- Service Schedules
> Update search layout fields and compact layouts

- robot/pmm/tests/browser/Bulk_Service_Delivery/add_pe_on_BSDT.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
> [Robot] added test for service participant quick action

- lib/admin_profile.xml
// Internal dev / qa flow only.
> Fix update admin profile missing custom tabs

- lib/admin_profile.xml
// Fix for internal tooling only
~~Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: W-0000000: Work Name (https://github.com/SalesforceFoundation/PMM/pull/303)~~
> Move missing tab fix to master

- force-app/main/default/lwc/recentSessions/recentSessions.html
- force-app/main/default/staticresources/pmm/recentSessionsOverrides.css
- Scope the css on the recent sessions component to prevent bleed to other custom components
~~Any net new LWC work has Sa11y tests & 50% or above lines JEST test coverage~~ 
> Scope css to recent sessions component

- force-app/main/default/lwc/recentSessions/recentSessions.html
- force-app/main/default/lwc/recentSessions/recentSessions.js
[W-8895701](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000096i8dIAA/view)
> Date localization fix in Recent Sessions cmp

- unpackaged/post/reports/reports/ProgramManagementReportsUnpackaged/Past_Sessions_in_Pending_Status_jZH.report
> Unpackaged Report Fix

- force-app/main/default/objects/ProgramEngagement__c/fieldSets/SessionParticipantView.fieldSet-meta.xml
> Remove naics fields

- force-app/main/default/objects/ProgramEngagement__c/fieldSets/SessionParticipantView.fieldSet-meta.xml
> Remove developer org fields

- force-app/main/default/classes/ServiceDeliveryTriggerHandler.cls
- force-app/main/default/classes/ServiceDeliveryTriggerHandler_TEST.cls
- force-app/main/default/layouts/Contact-Program Management.layout-meta.xml
- force-app/main/default/layouts/ProgramEngagement__c-Program Engagement Layout.layout-meta.xml
> Last Service Date bug fix, add Consecutive Absences to page layouts

- force-app/main/default/classes/ServiceScheduleService_TEST.cls
> Fix flaky test: remove model assert and rely on inner object asserts.

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/layouts/Service__c-Service Layout.layout-meta.xml
- force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.html
- force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.js
- force-app/main/default/lwc/groupServiceDelivery/groupServiceDelivery.html
- force-app/main/default/lwc/groupServiceDelivery/groupServiceDelivery.js
- force-app/main/default/lwc/groupServiceDelivery/groupServiceDelivery.js-meta.xml
- force-app/main/default/lwc/visualPicker/visualPicker.css
- force-app/main/default/lwc/visualPicker/visualPicker.html
- force-app/main/default/objects/Service__c/fields/BulkServiceDeliveryFieldSet__c.field-meta.xml
- force-app/main/default/staticresources/pmm/bsdtOverrides.css
> Set Service Delivery defaults based on fields from selected service field set value

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.html
- force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.js
- force-app/main/default/lwc/groupServiceDelivery/groupServiceDelivery.html
- force-app/main/default/lwc/groupServiceDelivery/groupServiceDelivery.js
- force-app/main/default/lwc/participantAdder/participantAdder.html
- force-app/main/default/lwc/participantSelector/participantSelector.html
- force-app/main/default/lwc/participantSelector/participantSelector.js
- force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
- force-app/main/default/lwc/visualPicker/visualPicker.html
~~QE story level testing completed~~
> Add Participants Screen on BSDT Wizard

- cumulusci.yml
Changed default branch to main.
> Update git default branch in cumulusci.yml

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
- force-app/main/default/lwc/pubsub/pubsub.js
- force-app/main/default/lwc/serviceDeliveryModal/serviceDeliveryModal.html
- force-app/main/default/lwc/serviceDeliveryModal/serviceDeliveryModal.js
- force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
> BSDT Defaults refinements

- robot/pmm/resources/BulkServiceDeliveryPageObject.py
- robot/pmm/resources/locators_51.py
- robot/pmm/tests/browser/Bulk_Service_Delivery/add_pe_on_BSDT.robot
- robot/pmm/tests/browser/Bulk_Service_Delivery/group_service_delivery.robot
- robot/pmm/tests/browser/Bulk_Service_Delivery/individual_service_delivery.robot
> [Robot] added group service delivery tests

- robot/pmm/resources/ServiceSchedulePageObject.py
- robot/pmm/resources/locators_51.py
- robot/pmm/tests/browser/ServiceSchedule/new_service_schedule.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_filter.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
> [Robot] Filter on service schedule wizard screen 3

- robot/pmm/resources/BulkServiceDeliveryPageObject.py
- robot/pmm/tests/browser/Bulk_Service_Delivery/individual_service_delivery.robot
> [Robot] Manual Save on BSDT

- force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
- force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
> Add newly-not-required fields to perm sets

- requirements.txt
- scripts/label_audit.py
> Update label audit to enforce localizable flexipage tabs

- robot/pmm/resources/locators_51.py
- robot/pmm/tests/browser/Bulk_Service_Delivery/group_service_delivery.robot
> [Robot] Feature/robot bsdt filter

- robot/pmm/resources/ServiceSessionPageObject.py
- robot/pmm/resources/locators_51.py
- robot/pmm/resources/pmm.py
- robot/pmm/resources/pmm.robot
- robot/pmm/tests/browser/Attendance/attendance_summary.robot
- robot/pmm/tests/browser/Attendance/dim_attendance.robot
- robot/pmm/tests/browser/Attendance/update_attendance.robot
> [Robot] added test for attendance calculations

- force-app/main/default/layouts/Contact-Program Management.layout-meta.xml
- force-app/main/default/layouts/ProgramEngagement__c-Program Engagement Layout.layout-meta.xml
- force-app/main/default/layouts/ServiceSession__c-Service Session Layout.layout-meta.xml
- force-app/main/default/layouts/Service__c-Service Layout.layout-meta.xml
Added attendance status field to service delivery related list on 
1. Contact
2. PE
3. Service
4. Service session
> added attendance status field to related list

- cumulusci.yml
- scripts/Use_Alternate_Field_Sets.apex
- unpackaged/config/alternate_field_sets/objects/___NAMESPACE___ServiceDelivery__c/fieldSets/Alternate_no_service.fieldSet-meta.xml
> Field set automation - Added fieldset without Service field on SD

- robot/pmm/resources/BulkServiceDeliveryPageObject.py
- robot/pmm/resources/ContactPageObject.py
- robot/pmm/resources/HomePageObject.py
- robot/pmm/resources/ProgramEngagementPageObject.py
- robot/pmm/resources/ServiceSchedulePageObject.py
- robot/pmm/resources/ServiceSessionPageObject.py
- robot/pmm/resources/locators_51.py
- robot/pmm/resources/pmm.py
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen2.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
Added tests:
1. Upcoming service schedule
2. Add new session on screen 2
3. Warning message on screen 3 when number of participants exceeds capacity
> [Robot] Added/updated service schedule tests

- cumulusci.yml
> Add community login button to Contact layout

- force-app/main/default/classes/ServiceService_TEST.cls
// Added an equal to sign in the condition since service field can also be the first field in the fieldset
~~- [ ] Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: W-0000000: Work Name (https://github.com/SalesforceFoundation/PMM/pull/303)~~
~~- [ ] PR contains draft release notes~~
~~- [ ] QE story level testing completed~~
> Fixing beta test errors

- unpackaged/config/alternate_field_sets/objects/___NAMESPACE___ServiceDelivery__c/fieldSets/Alternate.fieldSet-meta.xml
- unpackaged/config/alternate_field_sets/objects/___NAMESPACE___ServiceDelivery__c/fieldSets/Alternate_no_service.fieldSet-meta.xml
> Fixed unpackaged fieldsets

- README.md
- package.json
- yarn.lock
Fixes dependabot issues
[W-9544954](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Q6tqYAC/view)
> Dependabot 232.1

- cumulusci.yml
> Opt into auto merge

- robot/pmm/resources/pmm.robot
- robot/pmm/tests/browser/ServiceSchedule/delete_future_sessions.robot
> [Robot] Delete future service sessions

- robot/pmm/resources/ServiceSessionPageObject.py
- robot/pmm/resources/locators_52.py
- robot/pmm/tests/browser/Attendance/update_attendance.robot
W-9505038
Added test to add field to attendance service deliveries fieldset and validate on attendance component.
> [Robot] Update fields on attendance service deliveries fieldset

- cumulusci.yml
> Fix indentation

- cumulusci.yml
- force-app/main/default/objects/Contact/fields/AttendanceRate__c.field-meta.xml
- force-app/main/default/objects/Contact/fields/AttendanceSummary__c.field-meta.xml
- force-app/main/default/objects/ProgramEngagement__c/fields/AttendanceRate__c.field-meta.xml
- force-app/main/default/objects/ProgramEngagement__c/fields/AttendanceSummary__c.field-meta.xml
- force-app/main/default/objects/ServiceSession__c/fields/AttendanceRate__c.field-meta.xml
- force-app/main/default/objects/ServiceSession__c/fields/AttendanceSummary__c.field-meta.xml
- force-app/main/default/objects/Service__c/fields/AttendanceRate__c.field-meta.xml
- force-app/main/default/objects/Service__c/fields/AttendanceSummary__c.field-meta.xml
- Updates formulas for Attendance calculations so that reports don't show errors on divide by zero.
- We fixed the formulas for the Attendance Rate or Attendance Summary fields so that reports that contain these fields don't show errors when the related Number of Absent Service Deliveries or Number of Present Service Deliveries fields were null or set to Zero.
- Fixes #518 
> Formula Updates for Attendance

- cumulusci.yml
// Changes to internal tooling to regression org flow order
> Add data before push upgrading beta

- robot/pmm/tests/browser/Bulk_Service_Delivery/bsdt_fieldsets.robot
> [Robot] Switch fieldsets on bsdt

- robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
- robot/pmm/tests/browser/ProgramEngagement/autopopulate_pe_fields.robot
> [Robot] Fixed unstable tests

- force-app/main/default/lwc/sessionCard/sessionCard.html
Fixed Attendance Rate alignment on Recent Sessions component
[W-9992588](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000DbOX4YAN/view)
> Fixed Attendance Rate alignment on Recent Sessions component

- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js-meta.xml
Enables Bulk Service Delivery Tool (BSDT) for use in Experience Cloud
Thank you to @pedro-fernandez-30 for the contribution.
[W-9766139](https://gus.lightning.force.com/a07AH000000UHJrYAO)
> Enable BSDT in Experience Cloud

- force-app/main/default/classes/FieldSetService_TEST.cls
Also fixing case for method call in FieldSetService_TEST tests
> Updating variable name in FieldSetService_TEST tests

- unpackaged/config/alternate_field_sets/objects/___NAMESPACE___ServiceDelivery__c/fieldSets/AltAttendance.fieldSet-meta.xml
// Internal change only for our dev config. The field set included <availableFields> which is only allowed in Dev environments.
~~Link the pull request and work item by PR comment and Chatter post respectively, e.g. GUS: W-0000000: Work Name (https://github.com/SalesforceFoundation/PMM/pull/303)~~
~~All **acceptance criteria** have been met~~
~~Developer~~
~~Code Reviewer~~
~~QA~~
~~PR contains …
> Update Unpackaged Dev Config for Alt Attendance Field Set

- force-app/main/default/classes/ServiceScheduleService_TEST.cls
// This is a fix to a test that would occasionally fail.
> Fix Intermittent Test Failure

- robot/pmm/resources/HomePageObject.py
- robot/pmm/resources/ServiceSchedulePageObject.py
- robot/pmm/resources/locators_52.py
- robot/pmm/tests/browser/HomePage/homepage_components.robot
- robot/pmm/tests/browser/ServiceSchedule/new_service_schedule.robot
[T-7217264](https://gus.lightning.force.com/lightning/r/ADM_Test_Scenario__c/a80EE000000Lb4bYAC/view)
[T-3842208](https://gus.lightning.force.com/lightning/r/ADM_Test_Scenario__c/a80B00000001HgTIAU/view)
> [Robot] service session and schedule q3 test

- force-app/main/default/classes/AttendanceController.cls
- force-app/main/default/classes/AttendanceController_TEST.cls
- force-app/main/default/classes/ServiceDeliverySelector.cls
- force-app/main/default/classes/ServiceDeliverySelector_TEST.cls
- force-app/main/default/classes/ServiceDeliveryService.cls
- force-app/main/default/classes/ServiceSessionDomain.cls
- force-app/main/default/classes/ServiceSessionDomain.cls-meta.xml
- force-app/main/default/classes/ServiceSessionDomain_TEST.cls
- force-app/main/default/classes/ServiceSessionDomain_TEST.cls-meta.xml
- force-app/main/default/classes/ServiceSessionService.cls
- force-app/main/default/classes/ServiceSessionService_TEST.cls
- force-app/main/default/lwc/attendance/attendance.js
- force-app/main/default/lwc/attendanceRow/attendanceRow.css
- force-app/main/default/lwc/attendanceRow/attendanceRow.html
- force-app/main/default/lwc/attendanceRow/attendanceRow.js
- force-app/main/default/objects/ServiceSession__c/fields/OmittedContactIds__c.field-meta.xml
- Tracks when attendance records are omitted so that future interactions with the tracking attendance will remember who was omitted.
> Track omitted attendance rows.

- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
> Fixes an issue where the default values on the Add Service Delivery Modal were not resetting.

- force-app/main/default/lwc/attendanceRow/attendanceRow.js
- force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
- force-app/main/default/lwc/reviewSessions/reviewSessions.html
- force-app/main/default/lwc/reviewSessions/reviewSessions.js
- force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.js
// No PR notes needed, fixes issues in 240 that have not yet been released.
> Do not set time if null on back and do not duplicate service sessions on back.

- force-app/main/default/labels/CustomLabels.labels-meta.xml
// Update for a new feature that has not yet been released. No release notes needed.
> Add text notifying the user they cannot modify or remove existing sessions

- force-app/main/default/lwc/participantSelector/participantSelector.css
- force-app/main/default/lwc/participantSelector/participantSelector.html
- force-app/main/default/lwc/participantSelector/participantSelector.js
- Added 1s debounce to search for participant selector
- Display spinner when search is in progress
> WIP: Feature/240  search updates

- .github/CODEOWNERS
> Update Codeowners Conflict

- force-app/main/default/lwc/attendance/attendance.js
- Fixes an issue to prevent accidental duplicate saves when recording attendance.
- Fixes [W-11564923](https://gus.lightning.force.com/lightning/r/a07EE000013ZHi9YAG/view)
> Prevent duplicate saves on when recording attendance.

- force-app/main/default/applications/Program_Management.app-meta.xml
- force-app/main/default/lwc/attendance/attendance.css
- force-app/main/default/lwc/attendance/attendance.html
- force-app/main/default/lwc/attendance/attendance.js-meta.xml
Allows PMM App to be used in mobile
First pass at mobile attendance heading rework
> PMM App Mobile with Attendance Heading

- force-app/main/default/lwc/attendance/attendance.css
- force-app/main/default/lwc/attendance/attendance.html
- force-app/main/default/lwc/attendanceRow/attendanceRow.html
- force-app/main/default/lwc/attendanceRow/attendanceRow.js
Updates Attendance component rows for use in mobile app
> Mobile Attendance Rows

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
Adds a message to alert users that BSDT is not compatible with small form factors in the mobile app.
> BSDT Small Factor Message

- force-app/main/default/classes/ServiceDeliveryService.cls
Fixes an issue where the delivery date could be set to tomorrow depending on timezone.
> Improved Delivery Date handling

- robot/pmm/resources/ServiceSchedulePageObject.py
- robot/pmm/resources/locators_52.py
- robot/pmm/resources/pmm.py
- robot/pmm/resources/pmm.robot
- robot/pmm/tests/browser/Bulk_Service_Delivery/group_service_delivery.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
> [Robot] Added test for creating custom metadata bucketed values

- force-app/main/default/aura/addMoreParticipants/addMoreParticipants.cmp
- force-app/main/default/aura/addMoreSessions/addMoreSessions.cmp
- force-app/main/default/aura/createServiceSchedule/createServiceSchedule.cmp
Fixes scrolling issue with Service Schedule wizard when content is tall.
> CSS Adjustments Service Schedule Wizard

- robot/pmm/resources/pmm.py
- robot/pmm/tests/browser/Attendance/update_attendance.robot
- robot/pmm/tests/browser/Bulk_Service_Delivery/group_service_delivery.robot
- robot/pmm/tests/browser/Bulk_Service_Delivery/individual_service_delivery.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_filter.robot
- robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
> [Robot] updated q3 bsdt tests

- force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
Updates BSDT Save button to prevent multiple records being created if clicked more than once.
> Debounce BSDT Save Button

- force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
Addresses a modal error by limiting the times that we call the close event.  
> Service Schedule Modal Error

- .github/CODEOWNERS
> Make CODEOWNERS GUS-Aware

- cumulusci.yml
> Switch install security to admin only

- cumulusci.yml
> Update installer security to admin only

- force-app/main/default/classes/ProgramEngagementSelector.cls
- force-app/main/default/classes/ProgramEngagementSelector_TEST.cls
// Another [PR](https://github.com/SalesforceFoundation-emu/CaseMan/pull/1349) needed in CaseMan to fix all encryption issues.
- Fixed an issue where the Contact Name could not be shield encrypted.
> Remove order by and filter by Contact name.
